import {
  washroom1,
  double_br6,
  double_br5,
  double_br4,
  double_br3,
  double_br2,
  double_br1,
  double_br,
  thumbnail,
  washroomHomestay,
  home_stay6,
  home_stay5,
  home_stay4,
  home_stay3,
  home_stay2,
  home_stay1,
  topView,
  othersLocation,
  othersBeach4,
  othersBeach3,
  othersBeach,
  othersBeach2,
  nightView,
  beachViewNight,
  bonfire,
  bonfire1,
  bonfire2,
  bonfire3,
} from "./imports";

const Data = [
  {
    id: 1,
    image: double_br6,
    category: "Double Bedroom",
    name: "Double Bedroom",
  },
  // {
  //   id: 2,
  //   image: washroom1,
  //   category: "Double Bedroom",
  //   name: "Double Bedroom",
  // },
  // {
  //   id: 3,
  //   image: double_br,
  //   category: "Double Bedroom",
  //   name: "Double Bedroom",
  // },
  // {
  //   id: 4,
  //   image: double_br1,
  //   category: "Double Bedroom",
  //   name: "Double Bedroom",
  // },
  // {
  //   id: 5,
  //   image: double_br2,
  //   category: "Double Bedroom",
  //   name: "Double Bedroom",
  // },
  {
    id: 6,
    image: double_br3,
    category: "Double Bedroom",
    name: "Double Bedroom",
  },
  // {
  //   id: 7,
  //   image: double_br4,
  //   category: "Double Bedroom",
  //   name: "Double Bedroom",
  // },
  {
    id: 8,
    image: double_br5,
    category: "Double Bedroom",
    name: "Double Bedroom",
  },
  {
    id: 9,
    image: washroomHomestay,
    category: "Home Stay",
    name: "Home Stay",
  },

  // home stay
  {
    id: 9,
    image: thumbnail,
    category: "Home stay",
    name: "Home stay",
  },
  {
    id: 10,
    image: double_br,
    category: "Home stay",
    name: "Home stay",
  },
  {
    id: 11,
    image: home_stay6,
    category: "Home stay",
    name: "Home stay",
  },
  {
    id: 12,
    image: home_stay5,
    category: "Home stay",
    name: "Home stay",
  },
  {
    id: 13,
    image: home_stay4,
    category: "Home stay",
    name: "Home stay",
  },
  {
    id: 14,
    image: home_stay3,
    category: "Home stay",
    name: "Home stay",
  },
  {
    id: 15,
    image: home_stay2,
    category: "Home stay",
    name: "Home stay",
  },
  {
    id: 16,
    image: home_stay1,
    category: "Home stay",
    name: "Home stay",
  },
  {
    id: 17,
    image: topView,
    category: "Others",
    name: "Others",
  },
  {
    id: 18,
    image: othersLocation,
    category: "Others",
    name: "Others",
  },
  {
    id: 19,
    image: othersBeach4,
    category: "Others",
    name: "Others",
  },
  // {
  //   id: 20,
  //   image: othersBeach4,
  //   category: "Others",
  //   name: "Others",
  // },
  // {
  //   id: 21,
  //   image: othersBeach3,
  //   category: "Others",
  //   name: "Others",
  // },
  {
    id: 22,
    image: othersBeach,
    category: "Others",
    name: "Others",
  },
  {
    id: 23,
    image: othersBeach2,
    category: "Others",
    name: "Others",
  },
  // {
  //   id: 24,
  //   image: othersBeach3,
  //   category: "Others",
  //   name: "Others",
  // },
  {
    id: 25,
    image: nightView,
    category: "Others",
    name: "Others",
  },
  {
    id: 26,
    image: beachViewNight,
    category: "Others",
    name: "Others",
  },
  // {
  //   id: 27,
  //   image: nightView,
  //   category: "Others",
  //   name: "Others",
  // },
  // {
  //   id: 28,
  //   image: bonfire,
  //   category: "Others",
  //   name: "Others",
  // },
  {
    id: 29,
    image: bonfire1,
    category: "Others",
    name: "Others",
  },
  {
    id: 30,
    image: bonfire2,
    category: "Others",
    name: "Others",
  },
  // {
  //   id: 31,
  //   image: bonfire3,
  //   category: "Others",
  //   name: "Others",
  // },
];
export default Data;
