import {
  washroom1,
  double_br6,
  double_br5,
  double_br4,
  double_br3,
  double_br2,
  double_br1,
  double_br,
  thumbnail,
  washroomHomestay,
  home_stay6,
  home_stay5,
  home_stay4,
  home_stay3,
  home_stay2,
  home_stay1,
  topView,
  othersLocation,
  othersBeach4,
  othersBeach3,
  othersBeach,
  othersBeach2,
  nightView,
  beachViewNight,
  bonfire,
  bonfire1,
  bonfire2,
  bonfire3,
} from "./imports";

const Data = [
  {
    id: 1,
    image: washroom1,
    category: "Double Bedroom",
    name: "Double Bedroom",
  },
  {
    id: 2,
    image: double_br6,
    category: "Double Bedroom",
    name: "Double Bedroom",
  },
  {
    id: 3,
    image: double_br,
    category: "Double Bedroom",
    name: "Double Bedroom",
  },
  {
    id: 4,
    image: double_br1,
    category: "Double Bedroom",
    name: "Double Bedroom",
  },
  {
    id: 5,
    image: double_br2,
    category: "Double Bedroom",
    name: "Double Bedroom",
  },
  {
    id: 6,
    image: double_br3,
    category: "Double Bedroom",
    name: "Double Bedroom",
  },
  {
    id: 7,
    image: double_br4,
    category: "Double Bedroom",
    name: "Double Bedroom",
  },
  {
    id: 8,
    image: double_br5,
    category: "Double Bedroom",
    name: "Double Bedroom",
  },
  {
    id: 9,
    image: washroomHomestay,
    category: "Double Bedroom",
    name: "Double Bedroom",
  },

  // home stay
  {
    id: 9,
    image: thumbnail,
    category: "Home stay",
    name: "Home stay",
  },
  {
    id: 10,
    image: double_br,
    category: "Home stay",
    name: "Home stay",
  },
  {
    id: 11,
    image: "../../assets/hotel_images/homestay/home_stay3.jpeg",
    category: "Home stay",
    name: "Home stay",
  },
  {
    id: 12,
    image: "../../assets/hotel_images/homestay/home_stay4.jpeg",
    category: "Home stay",
    name: "Home stay",
  },
  {
    id: 13,
    image: "../../assets/hotel_images/homestay/home_stay5.jpeg",
    category: "Home stay",
    name: "Home stay",
  },
  {
    id: 14,
    image: "../../assets/hotel_images/homestay/home_stay6.jpeg",
    category: "Home stay",
    name: "Home stay",
  },
  {
    id: 15,
    image: "../../assets/hotel_images/homestay/washroom.jpeg",
    category: "Home stay",
    name: "Home stay",
  },
];
export default Data;
